import Header from '../components/Header';
import SEO from '../components/SEO';

const googleScopes = [
  ['Gmail — read email', 'https://www.googleapis.com/auth/gmail.messages.readonly', 'Read messages to find, summarize, and extract information needed for a request. This permission cannot modify or delete email.'],
  ['Gmail — create drafts', 'https://www.googleapis.com/auth/gmail.drafts.create', 'Compose and create email drafts at the user’s request. Robin does not send email with this permission; the user reviews and sends the draft.'],
  ['Google Calendar', 'https://www.googleapis.com/auth/calendar.events.owned', 'Read, create, update, and delete events on calendars owned by the user, only in response to instructions or explicitly enabled workflows.'],
  ['Google Drive, Docs, Sheets, and Slides', 'https://www.googleapis.com/auth/drive.file', 'Create files and work with files created through the application or explicitly made available to it. It does not provide unrestricted access to every existing file in a user’s Google Drive.'],
];

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="border-t border-neutral-200 py-10 first:border-t-0 first:pt-0"><h2 className="mb-5 font-display text-2xl font-medium tracking-tight text-neutral-950 sm:text-3xl">{title}</h2><div className="space-y-4 text-base font-light leading-relaxed text-neutral-700">{children}</div></section>;
}

function List({ children }: { children: React.ReactNode }) {
  return <ul className="list-disc space-y-2 pl-5 marker:text-[#607D99]">{children}</ul>;
}

export default function PrivacyPolicyPage() {
  return <div className="min-h-screen bg-neutral-50 text-neutral-900">
    <SEO title="Privacy Policy | Atom8 Studio Virtual Assistant" description="Learn how the Atom8 Studio Virtual Assistant processes, stores, protects, and deletes information, including data accessed through Google Workspace integrations." canonical="https://atom8studio.com/virtual-assistant/privacy" />
    <Header links={[{ href: '/', label: 'Atom8 Studio' }, { href: '/robin', label: 'Robin' }]} ctaHref="mailto:info@atom8studio.com" ctaLabel="Contact us" />
    <main className="pt-20">
      <div className="border-b border-neutral-200 bg-white"><div className="mx-auto max-w-4xl px-6 py-16 lg:px-8 lg:py-24">
        <p className="mb-5 font-display text-xs font-semibold uppercase tracking-widest text-[#607D99]">Atom8 Studio Virtual Assistant</p>
        <h1 className="max-w-3xl font-display text-4xl font-medium tracking-tight text-neutral-950 sm:text-5xl">Privacy Policy</h1>
        <p className="mt-6 text-lg font-light leading-relaxed text-neutral-600">Effective date: September 27, 2026</p>
      </div></div>
      <article className="mx-auto max-w-4xl px-6 py-14 lg:px-8 lg:py-20">
        <Section title="Introduction"><p>This Privacy Policy applies to the Atom8 Studio Virtual Assistant (also called Robin), an AI-powered assistant provided by Atom8 Studio. The Virtual Assistant may use Hermes Agent technology as part of its implementation.</p><p>The Virtual Assistant can interact with users through supported communication channels, including WhatsApp and Telegram. Users may optionally connect third-party services such as Google Workspace. Connecting Google Workspace requires explicit authorization through Google’s OAuth consent process. Atom8 Studio does not receive or store your Google password.</p></Section>
        <Section title="Information We Process"><p>Depending on how you use the Virtual Assistant, Atom8 Studio may process:</p><List><li>Messages, requests, and instructions submitted through WhatsApp or another supported interface.</li><li>Account and contact information, agent and integration configuration, and OAuth credentials and tokens.</li><li>Conversation and session information where retained, agent memory where enabled, and operational logs, timestamps, and error information.</li><li>Information retrieved from third-party services you explicitly connect, including Google Workspace information necessary to fulfil a requested task.</li></List></Section>
        <Section title="Google Workspace Data"><p>Atom8 Studio accesses Google Workspace information only after you explicitly connect your Google account through Google’s OAuth authorization process. This information is accessed only to provide functionality you request or explicitly enable.</p><div className="space-y-5 pt-2">{googleScopes.map(([name, scope, purpose]) => <div key={scope} className="rounded-2xl border border-neutral-200 bg-white p-5"><h3 className="font-display text-lg font-medium text-neutral-950">{name}</h3><code className="mt-3 block break-all rounded-lg bg-neutral-100 px-3 py-2 text-xs text-neutral-700">{scope}</code><p className="mt-3">{purpose}</p></div>)}</div><p>The initial release intentionally uses <code className="rounded bg-neutral-100 px-1.5 py-0.5 text-sm">drive.file</code>, rather than broader Drive permissions, under the principle of least privilege. It does not request <code className="rounded bg-neutral-100 px-1.5 py-0.5 text-sm">drive.readonly</code> or unrestricted <code className="rounded bg-neutral-100 px-1.5 py-0.5 text-sm">drive</code> access.</p></Section>
        <Section title="How Google Workspace Data Is Used"><p>Google Workspace information is used only to provide functionality requested or explicitly enabled by the authenticated user—for example, finding or summarizing relevant email, answering a question using relevant information, creating an email draft, managing calendar events, or creating and working with authorized Docs, Sheets, Slides, and Drive files.</p><p>Google Workspace information is not sold, used for advertising or advertising profiles, transferred to data brokers, used to determine creditworthiness, used for unrelated commercial purposes, or used to train generalized, shared, or non-personalized AI or machine-learning models.</p></Section>
        <Section title="AI Processing"><p>The Virtual Assistant uses artificial intelligence services to understand requests, determine appropriate actions, and generate responses. When necessary to fulfil a request, relevant information may be transmitted directly to an approved AI model provider through its developer or API endpoint.</p><p>For a Google Workspace request, Robin may retrieve relevant information from your authorized account and securely transmit relevant portions to an approved AI model provider where necessary for the specific task. Atom8 Studio seeks to minimize the information sent and limit processing to what is reasonably necessary. Identifying information may be reduced or de-identified where practical.</p><p>Approved AI providers are used under business or API terms that do not permit prompt data to be used for model training. Where an environment is configured with a self-hosted model, Hermes can also operate with local model backends, such as vLLM or Ollama, for offline or network-air-gapped processing.</p><p className="rounded-xl border border-[#7E9BB7]/30 bg-[#7E9BB7]/10 p-4 font-medium text-neutral-800">Google Workspace API data is not used to develop, improve, or train generalized or non-personalized artificial intelligence or machine-learning models. It is not used to train shared AI models for other Atom8 Studio customers.</p></Section>
        <Section title="How Information May Flow"><p>Not every request uses every stage. Google Workspace is contacted only when a task requires it, and each stage should process only information reasonably necessary for the requested functionality.</p><div className="overflow-x-auto rounded-2xl bg-neutral-950 p-6 font-mono text-sm leading-7 text-neutral-200 whitespace-pre">User request (WhatsApp or another supported channel){'\n'}        ↓{'\n'}Robin{'\n'}        ↓{'\n'}Atom8 Studio managed infrastructure{'\n'}        ↓{'\n'}Approved AI model provider, where required{'\n'}        ↓{'\n'}Your authorized Google Workspace, where required{'\n'}        ↓{'\n'}Robin{'\n'}        ↓{'\n'}Response to you</div></Section>
        <Section title="Hermes Agent"><p>Atom8 Studio may use Hermes Agent technology as part of operating the Virtual Assistant. The <a className="font-medium text-[#607D99] underline underline-offset-4" href="https://hermesagent.homes/privacy-policy" target="_blank" rel="noreferrer">Hermes Agent Privacy Policy</a> provides additional information about Hermes-related technology and data handling.</p><p>That policy does not replace Atom8 Studio’s Privacy Policy or responsibilities. Atom8 Studio remains responsible for its own handling of customer and Google Workspace information.</p></Section>
        <Section title="Where Your Data Is Stored"><p>Your Virtual Assistant environment runs on a private virtual private server (VPS) managed for Atom8 Studio. Conversation logs, including Hermes <code className="rounded bg-neutral-100 px-1.5 py-0.5 text-sm">state.db</code> data, enabled memories, documents, configuration, and other persistent agent data reside on that private server rather than in a consumer AI application’s shared chat-history or profile database.</p><p>Credentials, tokens, and passwords are stored in server-side configuration or dedicated vaults and are not intentionally exposed in chat transcripts. Persistent customer data remains in the private VPS environment, subject to necessary backup, security, and infrastructure operations. Limited information may be sent to approved subprocessors only where required for a requested function, such as an AI model provider processing a task.</p></Section>
        <Section title="Messaging and Access Protections"><p>Hermes is configured with controls intended to limit who can interact with the Virtual Assistant. These may include allowlisted messaging users and direct-message policies, so unauthorized phone numbers or contacts cannot query the system.</p><p>In group conversations, mention gating may require an explicit mention before the Virtual Assistant processes a message. Group and private direct-message sessions use separate context and can have different permission rules, including more limited group access to files or tools than a private administrative conversation.</p></Section>
        <Section title="Local Processing and Execution Boundaries"><p>File indexing, code execution, database queries, document processing, and integrations are performed locally within the Virtual Assistant’s container on the private VPS. This allows information to be searched, processed, and organized without sending the underlying files or data to a third-party cloud service for those local operations.</p><p>Information leaves the private VPS only when needed to provide an explicitly requested integration or AI-processing function, such as communicating with WhatsApp, Google Workspace, or an approved AI model provider.</p></Section>
        <Section title="Service Providers and Subprocessors"><p>Atom8 Studio relies on selected providers to operate the Virtual Assistant, which may include managed cloud infrastructure and hosting, storage and backup, AI model, security and monitoring, and communications providers needed to support interfaces such as WhatsApp.</p><p>These providers may process limited information only where necessary to provide services to Atom8 Studio or fulfil requested functionality. Providers handling confidential customer information are expected to be subject to appropriate confidentiality, security, and data-processing obligations. Information is not provided to subprocessors for their independent advertising or marketing purposes.</p></Section>
        <Section title="Confidentiality"><p>Atom8 Studio treats customer information as confidential. We do not sell it, provide it to data brokers, share it for third-party advertising, use it to create advertising profiles, or use it for unrelated commercial purposes.</p><p>Access by Atom8 Studio personnel is restricted to situations where reasonably necessary to operate, maintain, secure, support, troubleshoot, or meet legal obligations for the service.</p></Section>
        <Section title="Google API Services User Data Policy"><p>Atom8 Studio’s use and transfer of information received from Google APIs adheres to the <a className="font-medium text-[#607D99] underline underline-offset-4" href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noreferrer">Google API Services User Data Policy</a>, including the Limited Use requirements.</p><p>Google Workspace information is not sold, used for advertising, transferred to data brokers, used to determine creditworthiness, or used to train or improve generalized or non-personalized AI or machine-learning models.</p></Section>
        <Section title="Security"><p>Atom8 Studio uses reasonable technical and organizational safeguards designed to protect customer information. These may include encryption in transit, secure managed cloud infrastructure, restricted infrastructure access, protection of OAuth credentials, logical isolation between customer environments, infrastructure monitoring, and appropriate authentication and access controls. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.</p></Section>
        <Section title="Disconnecting Google Workspace"><p>You remain in control of your Google authorization. You can revoke the Virtual Assistant’s Google Workspace access through Atom8 Studio’s integration or disconnection mechanism where available, or through the connected-app and security settings of your Google Account.</p><p>After authorization is revoked, the Virtual Assistant will no longer be able to retrieve new Google Workspace information using that authorization. When an integration is permanently disconnected or you request deletion, Atom8 Studio should remove the associated stored OAuth credentials.</p></Section>
        <Section title="Your Right to Delete Your Data"><p>You may request deletion of data held by Atom8 Studio by contacting <a className="font-medium text-[#607D99] underline underline-offset-4" href="mailto:info@atom8studio.com">info@atom8studio.com</a>.</p><p>Where applicable, deletion includes Google OAuth access and refresh tokens, stored Google integration information and persisted Workspace content, Hermes Agent local or persistent user data, conversation and session data, enabled memory, customer-specific configuration containing personal information, stored user content, customer-specific application data, and other personal information associated with your Virtual Assistant environment.</p><p>Deleting a customer environment is intended to remove its customer-specific persistent data. Backup copies may remain temporarily under Atom8 Studio’s backup-retention process and expire or be deleted under that process. Deletion may exclude information we are legally required to retain or minimal records reasonably required for security, fraud prevention, accounting, or legal compliance.</p></Section>
        <Section title="Data Retention"><p>Atom8 Studio retains customer information only as long as reasonably necessary to provide the Virtual Assistant, maintain authorized integrations, meet legitimate operational and security requirements, and comply with applicable legal obligations. OAuth credentials are retained only while necessary to maintain your authorized Google integration. When a customer ends the service or requests deletion, customer-specific persistent information should be deleted subject to applicable backup-retention and legal requirements.</p></Section>
        <Section title="Changes to This Privacy Policy"><p>Atom8 Studio may update this policy when the Virtual Assistant, Google permissions, data-handling practices, AI providers, material subprocessors, infrastructure practices, or applicable legal requirements change. We will update the effective date when material changes are published. Material Google Workspace changes will also require appropriate updates to the OAuth configuration and authorization flow.</p></Section>
        <Section title="Contact and Privacy Requests"><p>For privacy questions, data-access or deletion requests, or Google Workspace integration questions, contact Atom8 Studio at <a className="font-medium text-[#607D99] underline underline-offset-4" href="mailto:info@atom8studio.com">info@atom8studio.com</a>.</p></Section>
      </article>
    </main>
    <footer className="border-t border-neutral-900 bg-neutral-950 px-6 py-10 text-neutral-400 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 text-xs font-light md:flex-row"><a href="/" className="font-display text-lg font-semibold text-white">Atom8 Studio</a><div>© {new Date().getFullYear()} Atom8 Studio. All rights reserved.</div><a href="mailto:info@atom8studio.com" className="transition-colors hover:text-white">info@atom8studio.com</a></div></footer>
  </div>;
}
