import { useState } from 'react';
import { Bell, CalendarDays, ChevronLeft, ChevronRight, CreditCard } from 'lucide-react';
import Header from '../components/Header';
import SEO from '../components/SEO';
import budgetVideo from '../assets/videos/Budget.mp4';
import calendarVideo from '../assets/videos/Calendar.mp4';
import compareVideo from '../assets/videos/Compare.mp4';

const integrations = ['WhatsApp', 'Telegram', 'Google Calendar', 'Gmail & Outlook', 'Receipts & expenses'];
const steps = [
  ['01', 'Message Robin', "Text what you need, in plain language, the same way you'd message a colleague."],
  ['02', 'Robin takes action', 'It books the meeting, sets the reminder, or logs the expense — instantly, in the background.'],
  ['03', 'You get confirmation', "A short reply confirms it's done. Nothing to open, nothing to check later."],
];
const features = [
  [CalendarDays, 'Calendar', 'Books, moves, and confirms meetings without you touching a calendar app.'],
  [Bell, 'Reminders', 'Nudges you before deadlines, renewals, and follow-ups slip through the cracks.'],
  [CreditCard, 'Expenses', 'Logs spending from receipts and texts, and totals it up whenever you ask.'],
];
const videoDemos = [
  { title: 'Update expenses in seconds', description: 'Send a receipt or expense update by message and keep your business records current.', video: budgetVideo },
  { title: 'Schedule your next meeting', description: 'Ask Robin to find a time, book the calendar invite, and remind everyone involved.', video: calendarVideo },
  { title: 'Avoid information overload', description: 'Go through information, and turn everyday questions into clear actions.', video: compareVideo },
];

export default function VirtualAssistantLandingPage() {
  const [activeVideo, setActiveVideo] = useState(0);

  return (
    <div className="min-h-screen bg-[#F6F8F8] font-sans text-[#202A36] antialiased">
      <SEO title="Robin — Virtual AI Assistant for Busy Professionals | Atom8 Studio" description="Robin is a virtual assistant that books your calendar, sets reminders, and tracks your spending through WhatsApp or Telegram chat." canonical="https://atom8studio.com/virtual-assistant" />
      <Header links={[{ href: '#how', label: 'How it works' }, { href: '#video', label: 'Demo' }]} ctaLabel="Get started" />
      <main className="pt-20">
        <section className="mx-auto max-w-7xl px-6 pb-20 pt-20 lg:px-8 lg:pt-28"><div className="grid items-center gap-16 lg:grid-cols-2"><div><p className="inline-flex items-center rounded-full px-4 py-1.5 text-xs font-semibold text-neutral-800 bg-neutral-200/60 border border-neutral-300/30 mb-8 font-display tracking-wide uppercase">For busy professionals</p><h1 className="mb-5 max-w-2xl font-display text-5xl font-medium leading-[1.08] tracking-tight text-[#2C2C2A] sm:text-6xl">Free your head for what’s next</h1><p className="mb-8 max-w-xl text-lg leading-relaxed text-[#5B6B7C]">Less to remember. More to focus on. Message Robin like you would a colleague — it books your calendar, tracks your spending, and reminds you before you forget. No new app, no dashboard, just chat. Robin will handle it.</p><div className="flex flex-wrap gap-3"><a href="#contact" className="rounded-full bg-[#202A36] px-7 py-3.5 text-sm font-semibold text-[#F6F8F8] transition hover:bg-[#2c3a4a]">Start chatting</a><a href="#video" className="rounded-full border border-[#E1E6E9] px-7 py-3.5 text-sm font-semibold transition hover:bg-white">Watch how it works</a></div></div><div className="rounded-[20px] border border-[#E1E6E9] bg-white p-5 shadow-[0_24px_48px_-32px_rgba(32,42,54,0.25)]"><div className="mb-4 flex items-center gap-2 border-b border-[#E1E6E9] pb-4 text-sm text-[#5B6B7C]"><span className="h-2 w-2 rounded-full bg-[#7FBF8F]" />Robin · online</div><div className="space-y-2.5 text-sm"><div className="ml-auto max-w-[78%] rounded-2xl rounded-br-sm bg-[#202A36] px-4 py-3 text-[#F6F8F8]">schedule a call with the client Tuesday 2pm</div><div className="max-w-[78%] rounded-2xl rounded-bl-sm border border-[#E1E6E9] bg-[#F6F8F8] px-4 py-3">Done. Invite sent to 5 people.</div><div className="ml-auto max-w-[78%] rounded-2xl rounded-br-sm bg-[#202A36] px-4 py-3 text-[#F6F8F8]">remind me to submit expenses Friday</div><div className="max-w-[78%] rounded-2xl rounded-bl-sm border border-[#E1E6E9] bg-[#F6F8F8] px-4 py-3">Got it, I'll remind you.</div><div className="ml-auto max-w-[78%] rounded-2xl rounded-br-sm bg-[#202A36] px-4 py-3 text-[#F6F8F8]">how much did I spend on Grab this week</div><div className="inline-flex gap-1 rounded-2xl rounded-bl-sm border border-[#E1E6E9] bg-[#F6F8F8] px-4 py-3"><span className="h-1.5 w-1.5 rounded-full bg-[#5B6B7C]" /><span className="h-1.5 w-1.5 rounded-full bg-[#5B6B7C]" /><span className="h-1.5 w-1.5 rounded-full bg-[#5B6B7C]" /></div></div></div></div></section>
        <section id="integrations" className="border-y border-[#E1E6E9] bg-white px-6 py-24 lg:px-8"><div className="mx-auto max-w-7xl text-center"><p className="mb-3 text-sm font-semibold uppercase tracking-[0.08em] text-[#7E9BB7]">Works with what you already use</p><h2 className="mb-4 font-display text-3xl font-medium sm:text-4xl">No new app to download.</h2><p className="mx-auto max-w-xl text-lg text-[#5B6B7C]">Robin runs on the messaging apps and tools you use every day — nothing new to learn.</p><div className="mt-9 flex flex-wrap justify-center gap-3">{integrations.map(item => <span key={item} className="rounded-full border border-[#E1E6E9] bg-[#E7EDF2] px-5 py-2.5 text-sm font-medium">{item}</span>)}</div></div></section>
        <section id="video" className="px-6 py-24 lg:px-8"><div className="mx-auto max-w-5xl"><div className="mb-10 text-center"><p className="mb-3 text-sm font-semibold uppercase tracking-[0.08em] text-[#7E9BB7]">See it in action</p><h2 className="mb-4 font-display text-3xl font-medium sm:text-4xl">Three tasks. One conversation.</h2><p className="mx-auto max-w-xl text-lg text-[#5B6B7C]">See how Robin turns everyday messages into useful action.</p></div><div className="grid items-center gap-8 rounded-[20px] border border-[#E1E6E9] bg-white p-5 shadow-[0_24px_48px_-32px_rgba(32,42,54,0.25)] md:grid-cols-[1.15fr_.85fr] md:p-8"><video key={videoDemos[activeVideo].video} controls autoPlay muted playsInline className="w-full rounded-2xl border border-[#D3D1C7] bg-[#F0EADD] shadow-sm"><source src={videoDemos[activeVideo].video} type="video/mp4" />Your browser does not support the video tag.</video><div><p className="mb-3 text-sm font-semibold uppercase tracking-[0.08em] text-[#7E9BB7]">0{activeVideo + 1} / 0{videoDemos.length}</p><h3 className="mb-3 font-display text-2xl font-medium">{videoDemos[activeVideo].title}</h3><p className="leading-relaxed text-[#5B6B7C]">{videoDemos[activeVideo].description}</p><div className="mt-8 flex items-center gap-3"><button type="button" onClick={() => setActiveVideo((activeVideo - 1 + videoDemos.length) % videoDemos.length)} aria-label="Previous video" className="flex h-10 w-10 items-center justify-center rounded-full border border-[#E1E6E9] transition hover:bg-[#E7EDF2]"><ChevronLeft className="h-5 w-5" /></button><div className="flex gap-2" aria-label="Choose a video">{videoDemos.map((demo, index) => <button key={demo.title} type="button" onClick={() => setActiveVideo(index)} aria-label={`View ${demo.title}`} aria-current={index === activeVideo} className={`h-2 rounded-full transition-all ${index === activeVideo ? 'w-8 bg-[#202A36]' : 'w-2 bg-[#B7C3CE]'}`} />)}</div><button type="button" onClick={() => setActiveVideo((activeVideo + 1) % videoDemos.length)} aria-label="Next video" className="flex h-10 w-10 items-center justify-center rounded-full border border-[#E1E6E9] transition hover:bg-[#E7EDF2]"><ChevronRight className="h-5 w-5" /></button></div></div></div></div></section>
        <section id="how" className="bg-[#E7EDF2] px-6 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><p className="mb-3 text-sm font-semibold uppercase tracking-[0.08em] text-[#7E9BB7]">How it works</p><h2 className="mb-4 font-display text-3xl font-medium sm:text-4xl">Three steps. That's it.</h2><p className="text-lg text-[#5B6B7C]">No onboarding call, no setup wizard — just start typing.</p><div className="mt-12 grid gap-8 md:grid-cols-3">{steps.map(([number, title, description]) => <article key={number} className="rounded-[14px] border border-[#E1E6E9] bg-white p-7"><p className="mb-4 font-display text-sm font-semibold text-[#7E9BB7]">{number}</p><h3 className="mb-2 font-display text-xl font-medium">{title}</h3><p className="text-sm leading-relaxed text-[#5B6B7C]">{description}</p></article>)}</div></div></section>
        <section id="features" className="px-6 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><p className="mb-3 text-sm font-semibold uppercase tracking-[0.08em] text-[#7E9BB7]">What Robin handles</p><h2 className="font-display text-3xl font-medium sm:text-4xl">Your admin, off your plate.</h2><div className="mt-12 grid gap-6 md:grid-cols-3">{features.map(([Icon, title, description]) => <article key={title as string} className="rounded-[14px] border border-[#E1E6E9] bg-white p-7"><div className="mb-5 flex h-10 w-10 items-center justify-center rounded-[10px] bg-[#E7EDF2]"><Icon className="h-5 w-5" /></div><h3 className="mb-2 font-display text-xl font-medium">{title as string}</h3><p className="text-sm leading-relaxed text-[#5B6B7C]">{description as string}</p></article>)}</div></div></section>
        <section id="contact" className="bg-[#202A36] px-6 py-24 text-center text-[#F6F8F8] lg:px-8"><div className="mx-auto max-w-2xl"><h2 className="font-display text-3xl font-medium sm:text-4xl">Ready to focus on what matters?</h2><p className="mx-auto my-4 max-w-xl text-lg text-[#B7C3CE]">Start a conversation with Robin — no setup, no download.</p><a href="mailto:info@atom8studio.com?subject=Start chatting with Robin" className="inline-flex rounded-full bg-[#F6F8F8] px-7 py-3.5 text-sm font-semibold text-[#202A36] transition hover:bg-white">Start chatting</a></div></section>
      </main>
      <footer className="border-t border-[#E1E6E9] px-6 py-12 lg:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5 text-sm text-[#5B6B7C]"><span>Robin, by Atom8 Studio · Kuala Lumpur</span><div className="flex gap-6"><a href="mailto:info@atom8studio.com" className="hover:text-[#202A36]">Contact</a><a href="/" className="hover:text-[#202A36]">Atom8 Studio</a></div></div></footer>
    </div>
  );
}
