services:
  # ==========================================
  # DOBBIE
  # ==========================================
  hermes-agent-dobbie:
    image: ghcr.io/lisajlau/atom8-hermes:v0.1.1
    container_name: hermes_agent_dobbie
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data_dobbie:/opt/data
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
        reservations:
          cpus: 0.5
          memory: 2G
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`)"

  # ==========================================
  # BOB
  # ==========================================
  hermes-agent-2:
    image: ghcr.io/lisajlau/atom8-hermes:v0.1.1
    container_name: hermes_agent_2
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data_2:/opt/data
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
        reservations:
          cpus: 0.5
          memory: 2G
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`)"

  # ==========================================
  # RUDOLPH
  # ==========================================

  hermes-agent-rudolph:
    image: ghcr.io/lisajlau/atom8-hermes:v0.1.1
    container_name: hermes_agent_rudolph
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data_rudolph:/opt/data
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
        reservations:
          cpus: 0.5
          memory: 2G
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`)"

  # ==========================================
  # ATOM8 HERMES
  # ==========================================
  atom8-hermes-1:
      image: ghcr.io/lisajlau/atom8-hermes:v0.1.1
      container_name: atom8_hermes
      restart: unless-stopped
      env_file:
        - .env
      volumes:
        - ./data_5:/opt/data
      deploy:
        resources:
          limits:
            cpus: 2
            memory: 4G
          reservations:
            cpus: 0.5
            memory: 2G
      labels:
        - "traefik.enable=false"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`)"
